ALTER TRIGGER FZ223_PPA.TRG_PURCHASE_BUD DISABLE;

DECLARE
  MAX_IDX_NUM NUMBER;
  PROCEDURE UPDATE_OR_INSERT( P_NAME IN VARCHAR2,
                              P_TYPAL_KIND IN VARCHAR2,
                              P_METHOD_TYPE VARCHAR2,
                              P_HAS_PHASES IN NUMBER DEFAULT 0,
                              P_COMPETITIVE IN NUMBER DEFAULT 1,
                              P_IS_DIGITAL IN NUMBER DEFAULT 0,
                              P_IS_EXTENDED IN NUMBER DEFAULT 0,
                              P_ALLOWED_IN_CLAUSE IN NUMBER DEFAULT 1,
                              P_ALLOWED_IN_PLAN IN NUMBER DEFAULT 1) IS
  BEGIN

    UPDATE FZ223_PPA.PURCHASE SET TYPAL = 1,
      TYPAL_KIND = P_TYPAL_KIND,
      METHOD_TYPE = P_METHOD_TYPE,
      HAS_PHASES = P_HAS_PHASES,
      COMPETITIVE = P_COMPETITIVE,
      IS_DIGITAL = P_IS_DIGITAL,
      IS_EXTENDED = P_IS_EXTENDED,
      ALLOWED_IN_CLAUSE = P_ALLOWED_IN_CLAUSE,
      ALLOWED_IN_PLAN = P_ALLOWED_IN_PLAN
    WHERE NAME = P_NAME;
    IF(sql%rowcount = 0) THEN
      MAX_IDX_NUM := MAX_IDX_NUM + 1;
      INSERT INTO FZ223_PPA.PURCHASE
      (ID, INDEX_NUMBER, NAME, PHASES_NUMBER, HAS_PHASES, COMPETITIVE, IS_DIGITAL, IS_EXTENDED, IS_CHANGEABLE, STATUS, CREATED_AT, UPDATED_AT, METHOD_TYPE, TYPAL, TYPAL_KIND,
       ALLOWED_IN_CLAUSE, ALLOWED_IN_PLAN)
      VALUES (FZ223_PPA.SEQ_PURCHASE.NEXTVAL,
              MAX_IDX_NUM,
              P_NAME,
              0,
              P_HAS_PHASES,
              P_COMPETITIVE,
              P_IS_DIGITAL,
              P_IS_EXTENDED,
              0,
              'RELEVANT',
              to_date(SYSDATE,'DD-MM-RR'),
              to_date(SYSDATE,'DD-MM-RR'),
              P_METHOD_TYPE,
              1,
              P_TYPAL_KIND,
              P_ALLOWED_IN_CLAUSE,
              P_ALLOWED_IN_PLAN);
    END IF;
  END UPDATE_OR_INSERT;

BEGIN
  SELECT MAX(INDEX_NUMBER) INTO MAX_IDX_NUM FROM FZ223_PPA.PURCHASE WHERE AGENCY_ID IS NULL AND IS_CHANGEABLE = 0;
  
  -- UPDATE_OR_INSERT(...
  
  COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK ;

END;

ALTER TRIGGER FZ223_PPA.TRG_PURCHASE_BUD ENABLE;
