 SELECT
   C.OWNER,
   C.OBJECT_NAME,
   C.OBJECT_TYPE,
   B.SID,
   B.SERIAL#,
   B.STATUS,
   B.OSUSER,
   B.MACHINE
FROM
   V$LOCKED_OBJECT A ,
   V$SESSION B,
   DBA_OBJECTS C
WHERE
   B.SID = A.SESSION_ID
AND
   A.OBJECT_ID = C.OBJECT_ID
AND
   C.OBJECT_NAME = 'TABLE_NAME';
